server:
  port: 10008
spring:
  application:
    name: seata-order-micro-service
  cloud:
    alibaba:
      seata:
        #指定事务组名，需要和seata-server中的对应 /conf/file.conf
        tx-service-group: recall_order_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848 #指定nacos server地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_micro_service?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: QY1989424334
#配置seata日志输出
logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath*:mapper/*.xml