server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: QY1989424334
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice # user服务的服务名称
  cloud:
    nacos:
        server-addr: localhost:8848 # nacos服务地址
        discovery:
          cluster-name: HZ # 集群名称
          namespace: ed825780-6358-4045-acdf-c47a3c511bcc # dev环境
          ephemeral: false # 是否是临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url: # eureka的地址信息
#      defaultZone: http://localhost:10086/eureka
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则
ribbon:
    eager-load:
      enabled: true # 开启饥饿加载
      clients: userservice # 指定饥饿加载的服务名称