server:
  port: 80

spring:
  application:
    name: e-commerce-consumer-openfeign

# 配置eureka-client
eureka:
  client:
    register-with-eureka: true #将自己注册到Eureka-server
    fetch-registry: true
    service-url:
      #表示将自己注册到哪个eureka-server
      #这里我们将本微服务注册到EurekaServer 集群，使用逗号间隔
      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka

#logging:
#  level:
#    #对MemberFeignService 接口调用过程打印信息-Debug
#    com.hspedu.springcloud.service.MemberFeignService: debug

#ribbon:
#  #1. 设置feign客户端超时时间(openfeign默认支持ribbon)
#  #2. ReadTimeout: 8000 建立连接从服务提供方获取可用资源的所用的全部时间
#  #3. 时间单位是毫秒
#  ReadTimeout: 8000
#  #两端连接所用的时间
#  ConnectTimeout: 8000

